//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Api_Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_vw_1
    {
        public int EmployeeId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int Age { get; set; }
        public string Department { get; set; }
        public decimal Salary { get; set; }
        public System.DateTime HiredDate { get; set; }
        public int Expr1 { get; set; }
        public string Expr2 { get; set; }
        public string Expr3 { get; set; }
        public int Expr4 { get; set; }
        public string Expr5 { get; set; }
        public decimal Expr6 { get; set; }
        public System.DateTime Expr7 { get; set; }
    }
}
