//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Api_Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCHOOL
    {
        public int SchoolId { get; set; }
        public string SchoolName { get; set; }
        public string S_Address { get; set; }
        public Nullable<int> S_ZipCode { get; set; }
    }
}
